groups:
- name: pod-health-rules
  rules:
  - alert: PodNotHealthy
    expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0
    for: 2m
    labels:
      severity: critical
      send_to_email: 'true'
    annotations:
      summary: "Pod not healthy in {{ $labels.namespace }}"
      description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-running state for more than 2 minutes.\nCurrent status: {{ $labels.phase }}\nValue = {{ $value }}"