prometheus:
  service:
    type: NodePort
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'app-health-check'
        metrics_path: '/health'
        static_configs:
          - targets: ['web.default.svc.cluster.local:5000']  # Adjust this to match your actual service name and port
        scrape_interval: 10s

grafana:
  service:
    type: NodePort

alertmanager:
  service:
    type: NodePort
  config:
    global:
      resolve_timeout: 1m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'mouadoussalah2016@gmail.com'
      smtp_auth_username: 'mouadoussalah2016@gmail.com'
      smtp_auth_password: 'ffjv kiqc rkcx otfs'
      smtp_require_tls: true

    route:
      receiver: 'email-notifications'
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      routes:
        - receiver: 'email-notifications'
          match:
            send_to_email: 'true'

    receivers:
    - name: 'email-notifications'
      email_configs:
      - to: 'mouadoussalah2016@gmail.com'
        send_resolved: true