apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-email-alert
  labels:
    app: kube-prometheus-stack
    release: prometheus-stack
spec:
  groups:
  - name: test.rules
    rules:
    - alert: TestEmailAlert
      expr: vector(1)
      for: 1m
      labels:
        severity: critical
        send_to_email: 'true'
      annotations:
        summary: "Test Email Alert"
        description: "This is a test alert to verify email notifications."