---
- hosts: workers
  vars_files:
    - sec_vault.yml
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Install MicroK8s
      snap:
        name: microk8s
        classic: yes
        state: present

    - name: Add user to microk8s group
      user:
        name: mouad
        groups: microk8s
        append: yes

    - name: Create .kube directory
      file:
        path: /home/mouad/.kube
        state: directory
        owner: mouad
        group: mouad
        mode: '0755'

    - name: Change ownership of .kube directory
      file:
        path: /home/mouad/.kube
        owner: mouad
        group: mouad
        recurse: yes

    - name: Reset connection to allow user changes to affect ansible user
      meta: reset_connection

    - name: Ensure MicroK8s is running
      command: microk8s start
      changed_when: false

    - name: Wait for MicroK8s to be ready
      command: microk8s status --wait-ready
      changed_when: false

    - name: Enable necessary MicroK8s addons
      command: microk8s enable dns dashboard storage ingress
      changed_when: false

    - name: Create alias for kubectl
      lineinfile:
        path: /home/mouad/.bashrc
        line: 'alias kubectl="microk8s kubectl"'
        create: yes

    - name: Generate kubeconfig
      command: microk8s config
      register: kubeconfig_output
      changed_when: false

    - name: Save kubeconfig to file
      copy:
        content: "{{ kubeconfig_output.stdout }}"
        dest: /home/mouad/.kube/config
        owner: mouad
        group: mouad
        mode: '0600'

    - name: Install ArgoCD CLI
      get_url:
        url: https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        dest: /usr/local/bin/argocd
        mode: '0555'

    - name: Remove existing Appv2 directory
      file:
        path: /home/mouad/Appv2
        state: absent

    - name: Git clone
      tags: clonecodeapp
      git:
        repo: https://{{GITHUB_USER|urlencode}}:{{GITHUB_TOKEN|urlencode}}@github.com/mouad-oussalah/Appv2.git
        dest: /home/mouad/Appv2

    - name: Download Argo CD install.yaml
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        dest: /tmp/install.yaml

    - name: Check if Argo CD server is set to insecure
      ansible.builtin.shell: grep -q '/usr/local/bin/argocd-server --insecure' /tmp/install.yaml
      register: grep_result
      ignore_errors: true

    - name: Modify Argo CD install.yaml to set insecure mode
      ansible.builtin.shell: sed -i 's|/usr/local/bin/argocd-server|&\n        - --insecure|' /tmp/install.yaml
      when: grep_result.rc != 0

    - name: Set KUBECONFIG environment variable
      ansible.builtin.shell: |
        echo "export KUBECONFIG=/var/snap/microk8s/current/credentials/client.config" >> ~/.bashrc
        source ~/.bashrc
      args:
        executable: /bin/bash

    - name: Create argocd namespace
      ansible.builtin.command:
        cmd: microk8s kubectl create namespace argocd
      ignore_errors: yes

    - name: Wait for API server to be ready
      ansible.builtin.wait_for:
        timeout: 30

    - name: Apply Argo CD manifests
      ansible.builtin.command:
        cmd: microk8s kubectl apply -n argocd -f /tmp/install.yaml
      environment:
        KUBECONFIG: /var/snap/microk8s/current/ansible/credentials/client.config

    - name: Apply ingress_argocd.yaml
      ansible.builtin.command:
        cmd: microk8s kubectl apply -f ~/Appv2/ansible/ingress-argocd.yaml

    - name: Apply argocd-declarative-setup.yml
      ansible.builtin.command:
        cmd: microk8s kubectl apply -f ~/Appv2/argocd-declarative-setup.yml

    - name: Ensure correct permissions for Appv2 directory
      file:
        path: /home/mouad/Appv2
        owner: mouad
        group: mouad
        recurse: yes

    - name: Enable Prometheus, Grafana, and Alertmanager addons in MicroK8s
      command: microk8s enable prometheus

    - name: Wait for Prometheus and Grafana to be ready
      command: microk8s kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=prometheus -n monitoring --timeout=300s
      changed_when: false

    - name: Create monitoring namespace
      command: microk8s kubectl create namespace monitoring
      ignore_errors: yes

    - name: Apply Prometheus configuration
      command: microk8s kubectl apply -f /home/mouad/Appv2/prometheus-config.yml

    - name: Apply Grafana configuration
      command: microk8s kubectl apply -f /home/mouad/Appv2/grafana-config.yml

    - name: Apply Alertmanager configuration
      command: microk8s kubectl apply -f /home/mouad/Appv2/alertmanager-config.yml

    - name: Get Grafana service NodePort
      command: microk8s kubectl get svc -n monitoring grafana -o jsonpath='{.spec.ports[0].nodePort}'
      register: grafana_nodeport

    - name: Display Grafana access information
      debug:
        msg: "Access Grafana at http://{{ ansible_host }}:{{ grafana_nodeport.stdout }}"