---
- hosts: workers
  become: yes
  vars:
    current_hour: "{{ ansible_date_time.hour | int }}"
    current_day: "{{ ansible_date_time.weekday }}"
  tasks:
    - name: Start application (full capacity)
      when: 
        - current_hour >= 8 and current_hour < 18
        - current_day in ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
      block:
        - name: Scale deployment to full capacity
          command: microk8s kubectl scale deployment web --replicas=2

    - name: Scale down application (50% capacity)
      when:
        - current_hour >= 18 and current_hour < 21
        - current_day in ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
      command: microk8s kubectl scale deployment web --replicas=1

    - name: Stop application
      when: 
        - current_hour >= 21 or current_hour < 8 or current_day in ['Saturday', 'Sunday']
      block:
        - name: Scale down deployment
          command: microk8s kubectl scale deployment web --replicas=0