---
- name: Setup MicroK8s and Scaling Script
  hosts: workers
  become: yes
  vars:
    ansible_playbook_path: "/home/mouad/Appv2/ansible/microk8s_scaling_playbook.yml"  # Update this path
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Copy scaling script
      copy:
        src: scale_microk8s.sh
        dest: /usr/local/bin/scale_microk8s.sh
        mode: '0755'

    - name: Set up cron jobs for scaling
      cron:
        name: "{{ item.name }}"
        minute: "{{ item.minute }}"
        hour: "{{ item.hour }}"
        day: "{{ item.day }}"
        month: "{{ item.month }}"
        weekday: "{{ item.weekday }}"
        job: "{{ item.job }}"
        user: root
      loop:
        - name: "Scale MicroK8s Weekday Morning"
          minute: "0"
          hour: "8"
          day: "*"
          month: "*"
          weekday: "1-5"
          job: "/usr/bin/ansible-playbook {{ ansible_playbook_path }}"
        - name: "Scale MicroK8s Weekday Evening"
          minute: "0"
          hour: "18"
          day: "*"
          month: "*"
          weekday: "1-5"
          job: "/usr/bin/ansible-playbook {{ ansible_playbook_path }}"
        - name: "Scale MicroK8s Weekend Midnight"
          minute: "0"
          hour: "0"
          day: "*"
          month: "*"
          weekday: "6,0"
          job: "/usr/bin/ansible-playbook {{ ansible_playbook_path }}"

    - name: Ensure scaling script is executable
      file:
        path: /usr/local/bin/scale_microk8s.sh
        mode: '0755'

    - name: Run scaling script
      command: /usr/bin/ansible-playbook {{ ansible_playbook_path }}
      changed_when: false