    global:
      resolve_timeout: 1m
      slack_api_url: 'hxtxtxpsx://hooks.slack.com/services/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'
    receivers:
    - name: 'slack-notificaions'
      slack_configs:
      - channel: '#devops-counsel-alertmanager-demo'
        send_resolved: true
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: 'slack-notificaions'
      repeat_interval: 3h